linters:
  disable-all: false
  disable:
    - thelper
    - varnamelen
    - tagliatelle
#    - interfacer
    - wrapcheck
#    - deadcode
#    - exhaustivestruct
#    - golint
#    - ifshort
#    - maligned
#    - nosnakecase
#    - scopelint
#    - structcheck
#    - varcheck
linters-settings:
  gocyclo:
    min-complexity: 11
issues:
  exclude:
    - composite
run:
  tests: false
  go: "1.21"